name: Environments Variables Test

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  env_variables:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Secrets
        env:
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          echo "Username: $USERNAME"